/* eslint-env mocha */
'use strict'

// tests for search
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin')
const dirtyChai = require('dirty-chai')
mochaPlugin.chai.use(dirtyChai)
const expect = mochaPlugin.chai.expect
let wrapped = mochaPlugin.getWrapper('search', '../../../src/functions/search.js', 'search')
let AWS = require('aws-sdk-mock')
let AWS_SDK = require('aws-sdk')
AWS.setSDKInstance(AWS_SDK)

describe('search', () => {
  before((done) => {
    done()
  })

  it('implement tests here', () => {
    return wrapped.run({
      body: JSON.stringify({
        parameter: 'value'
      })
    }).then((response) => {
      console.log(`response: ${JSON.stringify(response)}`);
      expect(response).to.not.be.empty()
    })
  }).timeout(10000); 
})
